require_relative 'minigl/game_object'
require_relative 'minigl/map'
require_relative 'minigl/text'
require_relative 'minigl/forms'
require_relative 'minigl/localization'
require_relative 'minigl/particles'
